### PR TITLE
Allow users to select an endpoint, and cache their choice

### PR DESCRIPTION
**Pull request by matthewlang**
When attempting to load a `.ok` file:
* If the file exists, load it.
* Otherwise, check for the existence of a file containing a cached okpy endpoint choice in the user's home directory.
* If this exists, open a template `.ok` file (to be distributed alongside the assignment notebook), and replace any endpoint placeholder with the cached endpoint.
* If the cached endpoint does not exist, load a list of endpoint options and allow the user to choose their class.

Sample interaction:
```
> from cs1.notebooks import *
> ok_login('p8.ok')
Select a class:
	0. Lang
	1. Kirlin
0
=====================================================================
Assignment: Program 08
OK, version v1.18.1
=====================================================================

Successfully logged in as langma@gmail.com
```

Subsequent loads:
```
> from cs1.notebooks import *
> ok_login('p8.ok')

=====================================================================
Assignment: Program 08
OK, version v1.18.1
=====================================================================

Successfully logged in as langma@gmail.com
```

PR contains an example notebook and template, which will be removed.

## Update 5/19:
* Added option to ignore `ok` files and cached endpoints, forcing a re-selection of endpoint.
* Allows students to fix errors with `ok_login('...', ignore_cache=True)`.
* Alternative approach would be to have an API surface that deletes the cached endpoint file. That approach would also have to 1) look for a `.template` file and 2) delete the previously-written `ok` file if one exists, as well.

cc @CatieWelsh @betswms

### CODE REVIEW

**Comment by matthewlang** [comment]
Do we think this approach makes sense? This would allow everyone to have their own okpy endpoint, rather than have all sections using the same labs belong to the same okpy class.

**Review by pkirlin — APPROVED** [review]
Yeah, I'm ok with this.  I'm not teaching this in the fall, so I'll defer to others, however.  :-)  Thanks, @matthewlang!

**Review by CatieWelsh — APPROVED** [review]
This sounds good to me. I think every professor having their own okpy works best.

**Comment by matthewlang** [comment]
Thanks! Merging.

**Pull request merged**
